### ISSUE TITLE
svn llvm repo deprecated

### ISSUE THREAD

**Issue by jfferson** [androm3da/llvm-doc#2]
I tried to install the code from the svn repository of the llvm repo and I kept getting compiling errors. They are moving to the git version -- http://llvm.org/docs/GettingStarted.html#getting-started-with-llvm -- so downloading from git is more secure

**Comment by androm3da** [comment]
I'm aware of the transition to the github monorepo.  Thanks for the reminder.

This repository is syncing from a git mirror, I suppose I could redesign it to use the monorepo instead.

I'm pretty sure that this experiment of mine (this mirror in order to use readthedocs) was mostly unused/unnoticed.

I'm going to close your issue because I think it doesn't apply here, but go ahead and reopen it if I'm wrong.
